import = [
"~/.config/alacritty/themes/dracula.toml"
]

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Never"

[env]
TERM = "xterm-256color"

[font]
size = 16.5

[font.bold]
family = "JetBrainsMono Nerd Font"
[font.bold_italic]
family = "JetBrainsMono Nerd Font"
[font.italic]
family = "JetBrainsMono Nerd Font"
[font.normal]
family = "JetBrainsMono Nerd Font"


[font.offset]
x = 0
y = 1

[scrolling]
history = 2000

[window]
decorations = "buttonless"
opacity = 0.9

[window.padding]
x = 6
y = 6
